#!/bin/bash

#SBATCH --job-name=build_anthology       
#SBATCH -A [ACCOUNT NAME]       
#SBATCH -p free      
#SBATCH --error=logs/error_%x.txt 
#SBATCH --output=logs/out_%x.txt             
#SBATCH --nodes=1               
#SBATCH --ntasks=1              
#SBATCH --cpus-per-task=1       
#SBATCH --time=0:02:00          

dir="selected_haikus"
outfile="haiku_anthology.txt"

: > $outfile

for file in "$dir"/*; do
    awk 'FNR==1 && NR!=1 {print ""} 1' $file >> $outfile
done
