#!/bin/bash

#SBATCH --job-name=haiku        
#SBATCH -A [ACCOUNT NAME]       
#SBATCH -p free                 
#SBATCH --nodes=1               
#SBATCH --ntasks=1              
#SBATCH --cpus-per-task=1       
#SBATCH --time=0:02:00          

dir="selected_haikus"
outfile="anthology.txt"

# Loop through regular files only
for file in "$dir"/*; do
    if [ -f "$file" ]; then
        cat "$file" >> "$outfile"
        echo >> "$outfile"   # add separating newline
    fi
done
