#!/bin/bash

#SBATCH -J Email_Test
#SBATCH -p free
#SBATCH --error=/path/to/logs/%A_%a.err
#SBATCH --output=/path/to/logs/%A_%a.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --array=1-2
#SBATCH --mail-type=END
#SBATCH --mail-user=panteater@uci.edu
#SBATCH -A [INSERT NAME]

source ./start_timer.sh

echo "${SLURM_ARRAY_TASK_ID}"
echo "Test error message" >&2

finish=$(date)

array_ID=${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}
outfile=/pub/dthuilli/logs/${array_ID}.out
errfile=/pub/dthuilli/logs/${array_ID}.err

source ./job_report.sh
