#!/bin/bash

#SBATCH -J Email_Test
#SBATCH -p free
#SBATCH --error=logs/%x_%A_%a.err
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --array=1-2
#SBATCH --mail-type=END
#SBATCH --mail-user=panteater@uci.edu
#SBATCH -A [INSERT NAME]

# Start a timer here
source ./start_timer.sh

echo "Array number ${SLURM_ARRAY_TASK_ID}"
echo "Test error message" >&2

# Finish the timer here and send an email job report!
source ./job_report.sh
